# Generated by Django 5.1.3 on 2024-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_human_supermarketicecream_children_icecream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='place',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('spares', models.ManyToManyField(null=True, to='bboard.spare')),
            ],
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Icecream',
        ),
        migrations.DeleteModel(
            name='SupermarketIceCream',
        ),
    ]
