# Generated by Django 5.1.3 on 2024-11-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_spare_remove_icecream_place_car_delete_children_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
